# Generated by Django 2.0.2 on 2018-02-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='artist.Artist', verbose_name='아티스트 목록'),
        ),
        migrations.AddField(
            model_name='album',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to='album', verbose_name='커버 이미지'),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
