# Generated by Django 2.0.2 on 2018-02-23 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_date', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melon_song_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='멜론 Song ID')),
                ('title', models.CharField(max_length=50, verbose_name='곡 제목')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='장르')),
                ('lyrics', models.TextField(blank=True, verbose_name='가사')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album', verbose_name='앨범')),
                ('artists', models.ManyToManyField(blank=True, to='artist.Artist', verbose_name='아티스트 목록')),
            ],
        ),
        migrations.AddField(
            model_name='artistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Song'),
        ),
    ]
