# Generated by Django 2.0.2 on 2018-02-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180208_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=100, verbose_name='장르'),
        ),
    ]
