# Generated by Django 2.0.2 on 2018-02-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='멜론 Song ID'),
        ),
    ]
