# Generated by Django 2.0.2 on 2018-02-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20180221_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='melon_id',
            new_name='melon_song_id',
        ),
    ]
