# Generated by Django 2.0.2 on 2018-02-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to='album', verbose_name='커버 이미지'),
        ),
        migrations.AddField(
            model_name='album',
            name='melon_album_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='멜론 Album ID'),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
