# Generated by Django 2.0.2 on 2018-02-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180208_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='melon_album_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='멜론 Album ID'),
        ),
    ]
