# Generated by Django 2.0.2 on 2018-02-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20180221_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, to='artist.Artist', verbose_name='아티스트 목록'),
        ),
    ]
