# Generated by Django 2.0.2 on 2018-02-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='멜론 Artist ID'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('a', 'A형'), ('b', 'B형'), ('o', 'O형'), ('c', 'AB형'), ('x', '기타')], max_length=50, verbose_name='혈액형'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='본명'),
        ),
    ]
