# Generated by Django 2.0.2 on 2018-02-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artist_melon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='멜론 Artist ID'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='본명'),
        ),
    ]
