# Generated by Django 2.0.2 on 2018-02-28 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_auto_20180228_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistyoutube',
            name='url_img_cover',
            field=models.URLField(blank=True, verbose_name='커버 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_artists', through='artist.ArtistLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
